number_to_word = {
    1: "ONE",
    2: "TWO",
    3: "THREE",
    4: "FOUR",
    5: "FIVE",
    6: "SIX",
    7: "SEVEN",
    8: "EIGHT",
    9: "NINE",
    10: "TEN",
    11: "ELEVEN",
    12: "TWELVE",
    13: "THIRTEEN",
    14: "FOURTEEN",
    15: "FITHTEEN",
}

# "": ("", "", ""),

mnemonics = {
    "A": ("A", "▄ ▄▄", "a-PART"),
    "B": ("B", "▄▄ ▄ ▄ ▄", "BOB is the man"),
    "C": ("C", "▄▄ ▄ ▄▄ ▄", "CO-ca CO-la"),
    "D": ("D", "▄▄ ▄ ▄", "DRAC-u-la"),
    "E": ("E", "▄", "Eh?!"),
    "F": ("F", "▄ ▄ ▄▄ ▄", "Fi-tti-PAL-di"),
    "G": ("G", "▄▄ ▄▄ ▄", "GOOD GRAV-y"),
    "H": ("H", "▄ ▄ ▄ ▄", "hip-pi-ty hop"),
    "I": ("I", "▄ ▄", "did it"),
    "J": ("J", "▄ ▄▄ ▄▄ ▄▄", "in JAWS JAWS JAW"),
    "K": ("K", "▄▄ ▄ ▄▄", "KAN-dy KID"),
    "L": ("L", "▄ ▄▄ ▄ ▄", "los AN-ge-les"),
    "M": ("M", "▄▄ ▄▄", "MA-MA"),
    "N": ("N", "▄▄ ▄", "NAV-y"),
    "O": ("O", "▄▄ ▄▄ ▄▄", "HO HO HO"),
    "P": ("P", "▄ ▄▄ ▄▄ ▄", "a PIZ-ZA pie"),
    "Q": ("Q", "▄▄ ▄▄ ▄ ▄▄", "GOD SAVE the QUEEN"),
    "R": ("R", "▄ ▄▄ ▄", "a RABB-it"),
    "S": ("S", "▄ ▄ ▄", "sí-sí-sí"),
    "T": ("T", "▄▄", "TALL"),
    "U": ("U", "▄ ▄ ▄▄", "un-der WHERE?!"),
    "V": ("V", "▄ ▄ ▄ ▄▄", "vic-tor-y VEE"),
    "W": ("W", "▄ ▄▄ ▄▄", "the WORLD WAR"),
    "X": ("X", "▄▄ ▄ ▄ ▄▄", "CROSS at the DOOR"),
    "Y": ("Y", "▄▄ ▄ ▄▄ ▄▄", "YELL-ow YO-YO"),
    "Z": ("Z", "▄▄ ▄▄ ▄ ▄", "ZU-ZU pe-tal"),
}
